---

- name: Gather facts
  ansible.builtin.gather_facts: {}

- name: Setup MacOS environment
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Setup Ubuntu environment
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Setup WSL environment
  import_tasks: wsl.yml
  when: ansible_kernel is search("microsoft")

- name: Create local bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: 0755

- name: Install Oh My zsh
  import_tasks: zsh.yml

- name: Install dotfiles
  shell: 'sh -c "$(curl -fsLS get.chezmoi.io)" -- -b {{ ansible_env.HOME }}/.local/bin init --apply jaswinford'

- name: Add flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpaks

- name: Install flatpaks
  become: true
  community.general.flatpak:
    name:
      - ch.theologeek.Manuskript
      - com.discordapp.Discord
      - com.spotify.Client
      - com.valvesoftware.Steam
      - io.kinvolk.Headlamp
      - io.pdman_desktop.PodmanDesktop
      - net.cozic.joplin_desktop
      - org.videolan.VLC
  tags:
    - flatpaks

- name: Install browsers via flatpak
  become: true
  community.general.flatpak:
    name:
      - com.google.Chrome
      - org.chromium.Chromium
      - org.mozilla.firefox
  when: kah_env_use_flatpak_browsers
  tags:
    - flatpaks

