---

- name: Install CLI tools in Ubuntu
  become: true
  apt:
    name:
      - ansible
      - ansible-lint
      - flatpak
      - git
      - zsh
      - unzip
      - fonts-jetbrains-mono
      - fonts-powerline
      - tig
      - tmux
      - ripgrep
      - fd-find
      - jq
      - htop
      - python3-pip
      - xclip
      - moreutils
      - neovim
      - keychain
      - gnupg
      - luarocks
    state: present

- name: Add flathub
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpaks

- name: Install flatpaks
  become: true
  community.general.flatpak:
    name:
      - com.discordapp.Discord
      - com.spotify.Client
      - com.valvesoftware.Steam
      - io.kinvolk.Headlamp
      - md.obsidian.Obsidian
      - net.cozic.joplin_desktop
      - org.prismlauncher.PrismLauncher
      - org.videolan.VLC
  tags:
    - flatpaks

- name: Install browsers via flatpak
  become: true
  community.general.flatpak:
    name:
      - com.google.Chrome
      - org.chromium.Chromium
      - org.mozilla.firefox
  tags:
    - flatpaks
