---
- name: Add PPA repository with most recent version of wslu
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:wslutilities/wslu'
    state: present

- name: Install wslu in Ubuntu
  become: true
  ansible.builtin.apt:
    name:
      - wslu
    update_cache: true

